### ISSUE TITLE
Please never forget increasing versionCode for new releases

### ISSUE THREAD

**Issue by IzzySoft** [KipJM/Reykunyutsyip#2]
Unfortunately your hotfix release will reach no existing installation as you seem to have forgotten increasing `versionCode`:

    Binary files repo/com.kip.reykunyutsyip_3.apk and repo/com.kip.reykunyutsyip_1.3.5.apk differ

That means the already existing version also had `versionCode: 3`. There are 5 releases listed, which means it should have been at least `versionCode: 5` by now :wink:

**Comment by IzzySoft** [comment]
Oh, PS, while I'm here:

    ! repo/com.kip.reykunyutsyip_3.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)

That can easily be avoided with a tiny addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by KipJM** [comment]
Hiya! Thanks for pointing that out! I have fixed the build and have removed the Google dependency blob
Commit: https://github.com/KipJM/Reykunyutsyip/commit/88df0cbf4ae00e62c7b1a998ad9684aeb16cc79f
thanks again!

**Comment by IzzySoft** [comment]
Thanks! That worked out fine:

```
 iod repo get com.kip.reykunyutsyip
com.kip.reykunyutsyip: looking for 'https://api.github.com/repos/KipJM/Reykunyutsyip/releases'
com.kip.reykunyutsyip: checking tag '1.3.5'
com.kip.reykunyutsyip: lastRelNo set to '1.3.5', checking for files
com.kip.reykunyutsyip: Upstream file date (2024-09-03 02:39) is newer than ours (2024-09-02 18:06).
com.kip.reykunyutsyip: returning ['1.3.5','https://github.com/KipJM/Reykunyutsyip/releases/download/1.3.5/reykunyutsyip-1-3-5-fixed.apk',1725323970]
com.kip.reykunyutsyip: 1.3.0/1.3.5, https://github.com/KipJM/Reykunyutsyip/releases: https://github.com/KipJM/Reykunyutsyip/releases/download/1.3.5/reykunyutsyip-1-3-5-fixed.apk
- Grabbing update for com.kip.reykunyutsyip: OK
- Checking 'repo/com.kip.reykunyutsyip_5.apk' for libraries and malware …
- Checking the app's AndroidManifest.xml …
com.kip.reykunyutsyip: check if repo contains FUNDING.yml
com.kip.reykunyutsyip: looking for 'https://api.github.com/repos/KipJM/Reykunyutsyip/contents/.github'
com.kip.reykunyutsyip: looking for 'https://api.github.com/repos/KipJM/Reykunyutsyip/contents/'
com.kip.reykunyutsyip: looking for 'https://api.github.com/repos/KipJM/.github/contents/'
com.kip.reykunyutsyip: Github reports "Not Found" for https://api.github.com/repos/KipJM/.github/contents/
com.kip.reykunyutsyip: no FUNDING.yml detected.
com.kip.reykunyutsyip: no Fastlane configured, skipping Fastlane check.
```

So this update will [become available here](https://apt.izzysoft.de/packages/com.kip.reykunyutsyip) with the next sync around 6 pm UTC. Oh: be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) and link there e.g. from your Readme if you wish :wink:

**Comment by KipJM** [comment]
thanks! I sure will! :)

**Comment by KipJM** [comment]
Hi! I just want to clarify that the only data the app downloads is from the domain reykunyu.lu, which has its source code in the github link mentioned in the readme. It does not download any data from github (as I know of)
None of the data(dictionary, art, audio) is owned by me, they are all downloaded from Reykunyu. While the app and Reykunyu (and probably others) is allowed to download and use these data and art. While the dictionary data is using the CC license, the art and audio are copyright to their artists, they are not owned by either me or the Reykunyu website.

**Comment by IzzySoft** [comment]
Thanks also for the notes! Updated that accordingly (effective with the next sync). Quite mixed stuff: libre, but also NC or maybe even proprietary content according to the "credits" on the site, so I've left it with NonFreeNet still but just replaced Gitub with reykunyu.lu in the description.

Thanks for adding the badge to your Readme :star_struck:

**Comment by KipJM** [comment]
No problem!
